### ISSUE TITLE
a couple of issues

### ISSUE THREAD

**Issue by kmkramer** [salt-formulas/salt-formula-docker#32]
I'm working on updating this formula to add support for docker-ce and adding the docker Ubuntu repos. I've got that piece working but I'm also having issues with the swarm init. I can get the master to init but there are no grains on that minion named 'docker_swarm_*' and thus no mine data to update. This causes other managers/workers to have an empty token when they run. Am I missing something? I don't actually see where you are getting the tokens after the swarm is first created or setting the grains on the master node.

my mine pillar

mine-data.sls
```
mine_functions:
  network.ip_addrs: []
  grains.item:
    - docker_swarm_tokens
    - docker_swarm_AdvertiseAddr
```
