### ISSUE TITLE
Can not install docker engine

### ISSUE THREAD

**Issue by wirwolf** [salt-formulas/salt-formula-docker#34]
Ubuntu 16.04

Pillars

```
docker:
  host:
    enabled: true
    options:
      insecure-registries:
        - 127.0.0.1
        - 10.0.0.1
      log-driver: json-file
      log-opts:
        max-size: 50m

```
Output 
```
----------
          ID: docker_packages
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-rd3c3717d33a04e6f957e74fef179e36e.scope.
                    E: Package 'docker-engine' has no installation candidate
     Started: 07:33:58.363041
    Duration: 4169.22 ms
     Changes:   
----------
          ID: /etc/default/docker
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: docker.host.docker_packages
     Started: 07:34:02.536706
    Duration: 0.022 ms
     Changes:   
----------
          ID: /etc/docker/daemon.json
    Function: file.managed
      Result: False
     Comment: One or more requisite failed: docker.host.docker_packages
     Started: 07:34:02.536833
    Duration: 0.008 ms
     Changes:   
----------
          ID: docker_service
    Function: service.running
        Name: docker
      Result: False
     Comment: One or more requisite failed: docker.host.docker_packages, docker.host./etc/docker/daemon.json, docker.host./etc/default/docker
     Started: 07:34:02.537660
    Duration: 0.012 ms
     Changes:   


```
