### ISSUE TITLE
docker daemon configuration

### ISSUE THREAD

**Issue by bbinet** [salt-formulas/salt-formula-docker#9]
I would like to customize the docker daemon configuration through the `/etc/docker/daemon.json` file:
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

Would it be possible to update the way `/etc/docker/daemon.json` is created in `docker/host.sls` so that it would be simple the json serialization of the `docker.host.daemon` pillar? Something like:
```
/etc/docker/daemon.json:
  file.managed:
    - contents: |
        {{ host.daemon | json(indent=2) | indent(8) }}
  - require:
    - pkg: docker_packages
  - watch_in:
    - service: docker_service
```
